export const QUESTION_GET_ALL = "GET_QUESTION_ALL";
export const QUESTION_GET_TITLE = "GET_QUESTION_TITLE";

export const DATABASE_GET_SUCCESS = "GET_DATABASE_SUCCESS";
export const DATABASE_GET_FAILURE = "GET_DATABASE_FAILURE";